
# tasks file for install
  - name: "Install Apache, MySQL, PHP, and other dependencies."
    apt: name="{{item}}" state=present
    with_items:
      - git
      - curl
      - sendmail
      - apache2
      - php7.0
      - php7.0-common
      - php7.0-mysql
      - php7.0-cli
      - php7.0-curl
      - php7.0-gd
      - php7.0-dev
      - php7.0-mcrypt
      - python-mysqldb
      - mysql-server

  - name: "Install PHP module for Apache"
    apt: name=libapache2-mod-php state=present

  - name: "Enable Apache rewrite module"
    apache2_module: name=rewrite state=present
    notify:
      - restart apache    

  - name: "Clean www directory"
    file:
      state: "{{item}}"
      path: "{{__http_dir}}"
    with_items:
      - absent
      - directory

  - name: "Start Apache and MySQL"
    service: "name={{ item }} state=started enabled=yes"
    with_items:
      - apache2
      - mysql

  - name: "Deploy www site"
    copy: src=. dest="{{__http_dir}}/"  mode=0664

